# syntax=docker/dockerfile:1

ARG PYTHON_VERSION=3.11.7
FROM python:${PYTHON_VERSION}-slim as base

# Set ENV
ENV DEBIAN_FRONTEND noninteractive
ENV PATH="${PATH}:/opt/cprocsp/bin/amd64/"
ENV PYTHONPATH "${PYTHONPATH}:/app/pycades"
ENV PYTHONUNBUFFERED=1

# Installation procees of pycades. Check official guide https://docs.cryptopro.ru/cades/pycades/pycades-build
RUN apt-get update
RUN apt-get install -y wget cmake build-essential libboost-all-dev python3-dev unzip

WORKDIR /app

# Need to pre-dowload your file from CryptoPro official site (version 5+) or chage this file for lower versions
COPY "linux-amd64_deb.tar" .

RUN wget 'https://cryptopro.ru/sites/default/files/products/cades/pycades/pycades.zip'
RUN tar xvf linux-amd64_deb.tar

RUN chmod +x /app/*.*

RUN /app/linux-amd64_deb/install.sh

RUN apt -o Apt::Get::Assume-Yes=true install /app/linux-amd64_deb/lsb-cprocsp-devel_5.0*.deb
RUN apt -o Apt::Get::Assume-Yes=true install  /app/linux-amd64_deb/lsb-cprocsp-base_5.0*.deb
RUN apt -o Apt::Get::Assume-Yes=true install  /app/linux-amd64_deb/cprocsp-pki-cades*.deb

RUN unzip pycades.zip

RUN cd pycades && \
mkdir build && \
cd build && \
cmake .. && \
make -j4 && \
chmod +x /app/pycades/build/pycades.so && \
cp /app/pycades/build/pycades.so /usr/local/lib

RUN rm /app/pycades.zip

RUN set -ex
